import torch
import time
import pickle
import os
from transformers import AutoModelForCausalLM, AutoTokenizer
from tqdm import tqdm

from inversion_optimisation.utils import load_dataset_tokens, DotDict, DATA_PATH, get_paper_summary_stats_new

# Baseline defined in https://huggingface.co/Corning/Reverse-Model-7B-348B
# 'LEDOM' — a causal LM trained right-to-left on reversed token sequences


def load_reverse_model(model_id="Corning/Reverse-Model-7B-348B", device="cuda"):
    """Load the LEDOM reverse language model and tokenizer."""
    tokenizer = AutoTokenizer.from_pretrained(
        model_id, use_fast=False, trust_remote_code=True
    )
    rev_model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto",
        torch_dtype=torch.bfloat16,
    ).eval()
    return rev_model, tokenizer


def generate_reverse(rev_model, tokenizer, prompt, max_new_tokens=200, **kwargs):
    """
    Generate text with the reverse language model.

    Since LEDOM was trained right-to-left, we:
      1. Tokenize the prompt
      2. Reverse the token order (drop the leading BOS so it lands at the end)
      3. Let the model generate forward (which is actually right-to-left)
      4. Reverse the full output back to normal reading order and decode
    """
    device = next(rev_model.parameters()).device

    # Encode & reverse
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids[0].tolist()

    # Reverse tokens; drop the first token (BOS=1) so it ends up at the
    # generation boundary rather than the start of the reversed sequence.
    reversed_ids = list(reversed(input_ids))[:-1]
    input_tensor = torch.tensor([reversed_ids], device=device)

    # Generate
    gen_kwargs = dict(
        max_new_tokens=max_new_tokens,
        num_beams=5,
        no_repeat_ngram_size=2,
        pad_token_id=tokenizer.eos_token_id,
    )
    gen_kwargs.update(kwargs)

    with torch.no_grad():
        output = rev_model.generate(input_tensor, **gen_kwargs)

    # Decode & un-reverse
    out_ids = output[0].tolist()
    # Clamp any out-of-vocab ids
    out_ids = [t if t < tokenizer.vocab_size else 0 for t in out_ids]
    out_ids.reverse()
    text = tokenizer.decode(out_ids, skip_special_tokens=True)
    return text


def reverse_model_text_search(cfg, model, device="cuda"):
    """
    Run the reverse model baseline on text-only inversion.

    Takes the same eval setup as other text-only methods:
    - Loads true input tokens (random/tinystories/reddit)
    - Generates greedy output text from the forward LLM
    - Feeds output text to the reverse model to recover input
    - Compares predicted tokens to true tokens

    Args:
        cfg: Config with input_len, output_len, num_targets, target_strategy,
             reverse_model_id, save_folder, model_name
        model: The forward TransformerLens model (for generating output text and tokenizing)
        device: Device string

    Returns:
        results: List of dicts with true_tokens, pred_tokens, found_solution, done_epochs
        elapsed_time: Total time for the inversion step
    """
    # Load true input tokens based on dataset strategy
    if cfg.target_strategy == "random":
        with open(DATA_PATH / f"true_tokens_{cfg.num_targets}_{cfg.input_len}.pkl", 'rb') as file:
            loaded_true_tokens = pickle.load(file).to("cpu")
    else:
        loaded_true_tokens = load_dataset_tokens(
            cfg.target_strategy, cfg.input_len, cfg.num_targets,
            include_bos=False, random_sentence=True, random_start=False, model=model
        )

    # Load the greedy output tokens (generated by forward model)
    true_tokens_loc = str(DATA_PATH / f"true_tokens_{cfg.num_targets}_{cfg.input_len}_{cfg.output_len}_greedy.pkl")
    with open(true_tokens_loc, 'rb') as file:
        loaded_true_outputs = pickle.load(file).to("cpu")

    # Load the reverse model
    model_id = cfg.get("reverse_model_id", "Corning/Reverse-Model-7B-348B")
    rev_model, rev_tokenizer = load_reverse_model(model_id, device)

    # Run inversion
    results = []
    elapsed_time = time.time()

    for i in tqdm(range(cfg.num_targets), desc="Reverse model inversion"):
        true_tokens_i = loaded_true_tokens[i]
        output_tokens_i = loaded_true_outputs[i]

        # Decode the forward model's output tokens to text
        output_text = model.tokenizer.decode(output_tokens_i.tolist())

        # Use reverse model to generate what came before
        reversed_text = generate_reverse(
            rev_model, rev_tokenizer, output_text,
            max_new_tokens=cfg.input_len * 4,  # generate enough tokens to cover input
        )

        # Tokenize the reversed text back with the forward model's tokenizer
        # and extract the last input_len tokens (the reverse model generates the prefix)
        pred_tokens_full = model.to_tokens(reversed_text)[0]

        # The reverse model output includes the original output text appended;
        # we want only the newly generated prefix tokens.
        # Take the first input_len tokens (skip BOS if present)
        offset = 1 if pred_tokens_full[0] == model.tokenizer.bos_token_id else 0
        pred_tokens_i = pred_tokens_full[offset:offset + cfg.input_len]

        # Pad if too short
        if len(pred_tokens_i) < cfg.input_len:
            pad = torch.zeros(cfg.input_len - len(pred_tokens_i), dtype=pred_tokens_i.dtype)
            pred_tokens_i = torch.cat([pred_tokens_i, pad])

        pred_tokens_i = pred_tokens_i[:cfg.input_len].to("cpu")
        true_tokens_i = true_tokens_i[:cfg.input_len].to("cpu")

        results.append({
            "true_tokens": true_tokens_i,
            "pred_tokens": pred_tokens_i,
            "found_solution": torch.equal(true_tokens_i, pred_tokens_i),
            "done_epochs": 1,
        })

    elapsed_time = time.time() - elapsed_time

    return results, elapsed_time
